name: "Lint and test and deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: TruffleHog secrets scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
          # cache: npm

      - name: install deps
        working-directory: app
        run: |
          npm i

      - name: run linting
        working-directory: app
        run: |
          npm run lint

      - name: run testing
        working-directory: app
        run: |
          npm run test

      # TODO: add cloudformation linting

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }
          AWS_DEFAULT_REGION: eu-west-2
          AWS_DEFAULT_OUTPUT: json
        with:
          name: JujharStack
          template: infra/my-cloudformation.yaml

      - run: echo "üçè This job's status is ${{ job.status }}."
